FROM elixir:1.5.2
ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash

WORKDIR /app
COPY ./pet_store.tar.gz ./
RUN tar xfz pet_store.tar.gz

ENTRYPOINT ["bin/pet_store"]
